//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockMount.Out.Sample.Utils.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Glossary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Glossary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockMount.Out.Sample.Utils.Language.Glossary", typeof(Glossary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is it ?.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddProduct.
        /// </summary>
        internal static string AddProductService {
            get {
                return ResourceManager.GetString("AddProductService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This function adds a new product with the given parameters.
        /// </summary>
        internal static string AddProductServiceDescription {
            get {
                return ResourceManager.GetString("AddProductServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        internal static string Authentication {
            get {
                return ResourceManager.GetString("Authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        internal static string Barcode {
            get {
                return ResourceManager.GetString("Barcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biggest Message Id.
        /// </summary>
        internal static string BiggestIntegrationMessageId {
            get {
                return ResourceManager.GetString("BiggestIntegrationMessageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get messages have id&apos;s less than this message id.
        /// </summary>
        internal static string BiggestIntegrationMessageIdDescription {
            get {
                return ResourceManager.GetString("BiggestIntegrationMessageIdDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biggest Order Detail Id.
        /// </summary>
        internal static string BiggestOrderDetailId {
            get {
                return ResourceManager.GetString("BiggestOrderDetailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get orders have id&apos;s less than this order id.
        /// </summary>
        internal static string BiggestOrderDetailIdDescription {
            get {
                return ResourceManager.GetString("BiggestOrderDetailIdDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        internal static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign Number.
        /// </summary>
        internal static string CampaignNumber {
            get {
                return ResourceManager.GetString("CampaignNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Career.
        /// </summary>
        internal static string Career {
            get {
                return ResourceManager.GetString("Career", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfirmOrRejectOrderItem.
        /// </summary>
        internal static string ConfirmOrRejectOrderItemService {
            get {
                return ResourceManager.GetString("ConfirmOrRejectOrderItemService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This method comfirms or rejects specific order item..
        /// </summary>
        internal static string ConfirmOrRejectOrderItemServiceDescription {
            get {
                return ResourceManager.GetString("ConfirmOrRejectOrderItemServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Id.
        /// </summary>
        internal static string CurrencyId {
            get {
                return ResourceManager.GetString("CurrencyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteProduct.
        /// </summary>
        internal static string DeleteProductService {
            get {
                return ResourceManager.GetString("DeleteProductService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This function deletes the product with the given Id.
        /// </summary>
        internal static string DeleteProductServiceDescription {
            get {
                return ResourceManager.GetString("DeleteProductServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentations.
        /// </summary>
        internal static string Documentation {
            get {
                return ResourceManager.GetString("Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DoLogin.
        /// </summary>
        internal static string DoLoginService {
            get {
                return ResourceManager.GetString("DoLoginService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use this method to login API service.&lt;br/&gt;
        ///You can use received ApiCode value to call other methods.&lt;br/&gt;
        ///You can recall this methot to get new ApiCode value when the session timed out&lt;br/&gt;
        ///You get (00006) error code when the session timed out..
        /// </summary>
        internal static string DoLoginServiceDescription {
            get {
                return ResourceManager.GetString("DoLoginServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-mail.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not authenticated !.
        /// </summary>
        internal static string Error00001 {
            get {
                return ResourceManager.GetString("Error00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is passive !.
        /// </summary>
        internal static string Error00002 {
            get {
                return ResourceManager.GetString("Error00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing parameter !.
        /// </summary>
        internal static string Error00003 {
            get {
                return ResourceManager.GetString("Error00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required field !.
        /// </summary>
        internal static string Error00004 {
            get {
                return ResourceManager.GetString("Error00004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad request !.
        /// </summary>
        internal static string Error00005 {
            get {
                return ResourceManager.GetString("Error00005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session timed out !.
        /// </summary>
        internal static string Error00006 {
            get {
                return ResourceManager.GetString("Error00006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Store !.
        /// </summary>
        internal static string Error10001 {
            get {
                return ResourceManager.GetString("Error10001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration Error !.
        /// </summary>
        internal static string Error60001 {
            get {
                return ResourceManager.GetString("Error60001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale item was shipped before !.
        /// </summary>
        internal static string Error60002 {
            get {
                return ResourceManager.GetString("Error60002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error !.
        /// </summary>
        internal static string Error99999 {
            get {
                return ResourceManager.GetString("Error99999", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error List.
        /// </summary>
        internal static string ErrorList {
            get {
                return ResourceManager.GetString("ErrorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute.
        /// </summary>
        internal static string Execute {
            get {
                return ResourceManager.GetString("Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        internal static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllUserMessage.
        /// </summary>
        internal static string GetAllUserMessageService {
            get {
                return ResourceManager.GetString("GetAllUserMessageService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This method gets all messages history of specific user..
        /// </summary>
        internal static string GetAllUserMessageServiceDescription {
            get {
                return ResourceManager.GetString("GetAllUserMessageServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetCurrencies.
        /// </summary>
        internal static string GetCurrenciesService {
            get {
                return ResourceManager.GetString("GetCurrenciesService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This service gets the available currencies in the system.
        /// </summary>
        internal static string GetCurrenciesServiceDescription {
            get {
                return ResourceManager.GetString("GetCurrenciesServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetIntegrationShipmentCompanies.
        /// </summary>
        internal static string GetIntegrationShipmentCompaniesService {
            get {
                return ResourceManager.GetString("GetIntegrationShipmentCompaniesService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This method gets shipment companies for specific e-commerce place..
        /// </summary>
        internal static string GetIntegrationShipmentCompaniesServiceDescription {
            get {
                return ResourceManager.GetString("GetIntegrationShipmentCompaniesServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetMessages.
        /// </summary>
        internal static string GetMessagesService {
            get {
                return ResourceManager.GetString("GetMessagesService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This method gets messages based on store and message type..
        /// </summary>
        internal static string GetMessagesServiceDescription {
            get {
                return ResourceManager.GetString("GetMessagesServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetProductCategories.
        /// </summary>
        internal static string GetProductCategoriesService {
            get {
                return ResourceManager.GetString("GetProductCategoriesService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This function gets the categories of a product source with a given id.
        /// </summary>
        internal static string GetProductCategoriesServiceDescription {
            get {
                return ResourceManager.GetString("GetProductCategoriesServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetProduct.
        /// </summary>
        internal static string GetProductService {
            get {
                return ResourceManager.GetString("GetProductService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This function returns a product given its Id.
        /// </summary>
        internal static string GetProductServiceDescription {
            get {
                return ResourceManager.GetString("GetProductServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetProductSources.
        /// </summary>
        internal static string GetProductSourcesService {
            get {
                return ResourceManager.GetString("GetProductSourcesService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This function gets the product sources.
        /// </summary>
        internal static string GetProductSourcesServiceDescription {
            get {
                return ResourceManager.GetString("GetProductSourcesServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetSales.
        /// </summary>
        internal static string GetSalesService {
            get {
                return ResourceManager.GetString("GetSalesService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This method gets sales based on store and order status..
        /// </summary>
        internal static string GetSalesServiceDescription {
            get {
                return ResourceManager.GetString("GetSalesServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetStores.
        /// </summary>
        internal static string GetStoresService {
            get {
                return ResourceManager.GetString("GetStoresService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This method gets current user store(s) information..
        /// </summary>
        internal static string GetStoresServiceDescription {
            get {
                return ResourceManager.GetString("GetStoresServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string GgCompleted {
            get {
                return ResourceManager.GetString("GgCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Case of Return.
        /// </summary>
        internal static string GgReturnedOrder {
            get {
                return ResourceManager.GetString("GgReturnedOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting Cargo.
        /// </summary>
        internal static string GgWaitingCargo {
            get {
                return ResourceManager.GetString("GgWaitingCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting Confirmation.
        /// </summary>
        internal static string GgWaitingConfirmation {
            get {
                return ResourceManager.GetString("GgWaitingConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting Payment.
        /// </summary>
        internal static string GgWaitingPayment {
            get {
                return ResourceManager.GetString("GgWaitingPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Guide.
        /// </summary>
        internal static string Guide {
            get {
                return ResourceManager.GetString("Guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks to StockMount Sample Project, you can learn how to login and use StockMount Service Methods.&lt;br/&gt;
        ///You can find a description for each single method.&lt;br/&gt;
        ///Welcome to world of StockMount !..&lt;br/&gt;
        ///&lt;br/&gt;
        ///&lt;a href=&quot;https://github.com/StockMount&quot; target=&quot;_blank&quot; &gt;Download this project from GitHub&lt;/a&gt;
        ///&lt;br/&gt;
        ///&lt;a href=&quot;http://www.stockmount.com/en-tr&quot; target=&quot;_blank&quot; &gt;Visit StockMount Website&lt;/a&gt;.
        /// </summary>
        internal static string HomePageDescription {
            get {
                return ResourceManager.GetString("HomePageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        internal static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image url.
        /// </summary>
        internal static string ImageUrl {
            get {
                return ResourceManager.GetString("ImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbox.
        /// </summary>
        internal static string Inbox {
            get {
                return ResourceManager.GetString("Inbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration.
        /// </summary>
        internal static string Integration {
            get {
                return ResourceManager.GetString("Integration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration Id.
        /// </summary>
        internal static string IntegrationId {
            get {
                return ResourceManager.GetString("IntegrationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration Order Code.
        /// </summary>
        internal static string IntegrationOrderCode {
            get {
                return ResourceManager.GetString("IntegrationOrderCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration Order Detail Id.
        /// </summary>
        internal static string IntegrationOrderDetailId {
            get {
                return ResourceManager.GetString("IntegrationOrderDetailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        internal static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses.
        /// </summary>
        internal static string Licenses {
            get {
                return ResourceManager.GetString("Licenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        internal static string Links {
            get {
                return ResourceManager.GetString("Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Price.
        /// </summary>
        internal static string MarketPrice {
            get {
                return ResourceManager.GetString("MarketPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Body.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Type.
        /// </summary>
        internal static string MessageType {
            get {
                return ResourceManager.GetString("MessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        internal static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money Transfer.
        /// </summary>
        internal static string MoneyTransfer {
            get {
                return ResourceManager.GetString("MoneyTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        internal static string N11ApprovedOrder {
            get {
                return ResourceManager.GetString("N11ApprovedOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string N11Completed {
            get {
                return ResourceManager.GetString("N11Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered.
        /// </summary>
        internal static string N11Delivered {
            get {
                return ResourceManager.GetString("N11Delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string N11NewOrder {
            get {
                return ResourceManager.GetString("N11NewOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        internal static string N11Rejected {
            get {
                return ResourceManager.GetString("N11Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipped.
        /// </summary>
        internal static string N11Shipped {
            get {
                return ResourceManager.GetString("N11Shipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Detail Id.
        /// </summary>
        internal static string OrderDetailId {
            get {
                return ResourceManager.GetString("OrderDetailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Id.
        /// </summary>
        internal static string OrderId {
            get {
                return ResourceManager.GetString("OrderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Status.
        /// </summary>
        internal static string OrderStatus {
            get {
                return ResourceManager.GetString("OrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StockMount Professional Integration Manager.
        /// </summary>
        internal static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Index.
        /// </summary>
        internal static string PageIndex {
            get {
                return ResourceManager.GetString("PageIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page index which to be retrieved.
        /// </summary>
        internal static string PageIndexDescription {
            get {
                return ResourceManager.GetString("PageIndexDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Id.
        /// </summary>
        internal static string ProductId {
            get {
                return ResourceManager.GetString("ProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Source Id.
        /// </summary>
        internal static string ProductSourceId {
            get {
                return ResourceManager.GetString("ProductSourceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        internal static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Type.
        /// </summary>
        internal static string RequestType {
            get {
                return ResourceManager.GetString("RequestType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string RequestUrl {
            get {
                return ResourceManager.GetString("RequestUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        internal static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows by page.
        /// </summary>
        internal static string RowsByPage {
            get {
                return ResourceManager.GetString("RowsByPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to how many item will be  retrieved.
        /// </summary>
        internal static string RowsByPageDescription {
            get {
                return ResourceManager.GetString("RowsByPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an integration.
        /// </summary>
        internal static string SelectIntegration {
            get {
                return ResourceManager.GetString("SelectIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send phone message.
        /// </summary>
        internal static string SendPhoneMessage {
            get {
                return ResourceManager.GetString("SendPhoneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send shipment information.
        /// </summary>
        internal static string SendShipmentInformation {
            get {
                return ResourceManager.GetString("SendShipmentInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SendUserMessage.
        /// </summary>
        internal static string SendUserMessageService {
            get {
                return ResourceManager.GetString("SendUserMessageService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This method allows you to send message to specific user..
        /// </summary>
        internal static string SendUserMessageServiceDescription {
            get {
                return ResourceManager.GetString("SendUserMessageServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent.
        /// </summary>
        internal static string Sent {
            get {
                return ResourceManager.GetString("Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string ServicesList {
            get {
                return ResourceManager.GetString("ServicesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set message read.
        /// </summary>
        internal static string SetMessageRead {
            get {
                return ResourceManager.GetString("SetMessageRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetMessageRead.
        /// </summary>
        internal static string SetMessageReadService {
            get {
                return ResourceManager.GetString("SetMessageReadService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This method sets specific message read..
        /// </summary>
        internal static string SetMessageReadServiceDescription {
            get {
                return ResourceManager.GetString("SetMessageReadServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetOrderShipmentInformation.
        /// </summary>
        internal static string SetOrderShipmentInformationService {
            get {
                return ResourceManager.GetString("SetOrderShipmentInformationService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This method sets shipment information of specific order item..
        /// </summary>
        internal static string SetOrderShipmentInformationServiceDescription {
            get {
                return ResourceManager.GetString("SetOrderShipmentInformationServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment Branch.
        /// </summary>
        internal static string ShipmentBranch {
            get {
                return ResourceManager.GetString("ShipmentBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment Company.
        /// </summary>
        internal static string ShipmentCompany {
            get {
                return ResourceManager.GetString("ShipmentCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment Company Id.
        /// </summary>
        internal static string ShipmentCompanyId {
            get {
                return ResourceManager.GetString("ShipmentCompanyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment Company Name.
        /// </summary>
        internal static string ShipmentCompanyName {
            get {
                return ResourceManager.GetString("ShipmentCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment Method.
        /// </summary>
        internal static string ShipmentMethod {
            get {
                return ResourceManager.GetString("ShipmentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment Tracking Code.
        /// </summary>
        internal static string ShipmentTrackingCode {
            get {
                return ResourceManager.GetString("ShipmentTrackingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StockMount Out Sample Project.
        /// </summary>
        internal static string SiteTitle {
            get {
                return ResourceManager.GetString("SiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smallest Message Id.
        /// </summary>
        internal static string SmallestIntegrationMessageId {
            get {
                return ResourceManager.GetString("SmallestIntegrationMessageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get messages have id&apos;s bigger than this message id.
        /// </summary>
        internal static string SmallestIntegrationMessageIdDescription {
            get {
                return ResourceManager.GetString("SmallestIntegrationMessageIdDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smallest Order Detail Id.
        /// </summary>
        internal static string SmallestOrderDetailId {
            get {
                return ResourceManager.GetString("SmallestOrderDetailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get orders have id&apos;s bigger than this order id.
        /// </summary>
        internal static string SmallestOrderDetailIdDescription {
            get {
                return ResourceManager.GetString("SmallestOrderDetailIdDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        internal static string SmApprovedOrder {
            get {
                return ResourceManager.GetString("SmApprovedOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string SmCompleted {
            get {
                return ResourceManager.GetString("SmCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered.
        /// </summary>
        internal static string SmDelivered {
            get {
                return ResourceManager.GetString("SmDelivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string SmNewOrder {
            get {
                return ResourceManager.GetString("SmNewOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        internal static string SmRejected {
            get {
                return ResourceManager.GetString("SmRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipped.
        /// </summary>
        internal static string SmShipped {
            get {
                return ResourceManager.GetString("SmShipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Cancelled.
        /// </summary>
        internal static string SpCustomerCancelled {
            get {
                return ResourceManager.GetString("SpCustomerCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Confirmed.
        /// </summary>
        internal static string SpCustomerConfirmed {
            get {
                return ResourceManager.GetString("SpCustomerConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Returned.
        /// </summary>
        internal static string SpCustomerReturned {
            get {
                return ResourceManager.GetString("SpCustomerReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specs.
        /// </summary>
        internal static string Specs {
            get {
                return ResourceManager.GetString("Specs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money Refund.
        /// </summary>
        internal static string SpMoneyRefund {
            get {
                return ResourceManager.GetString("SpMoneyRefund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money Transfer.
        /// </summary>
        internal static string SpMoneyTransfer {
            get {
                return ResourceManager.GetString("SpMoneyTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Suspensed.
        /// </summary>
        internal static string SpOrderSuspensed {
            get {
                return ResourceManager.GetString("SpOrderSuspensed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Confirmation.
        /// </summary>
        internal static string SpPaymentConfirmation {
            get {
                return ResourceManager.GetString("SpPaymentConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SanalPazar Cancelled.
        /// </summary>
        internal static string SpSanalPazarCancelled {
            get {
                return ResourceManager.GetString("SpSanalPazarCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller Cancelled.
        /// </summary>
        internal static string SpSellerCancelled {
            get {
                return ResourceManager.GetString("SpSellerCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment Not Received.
        /// </summary>
        internal static string SpShipmentNotReceived {
            get {
                return ResourceManager.GetString("SpShipmentNotReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment On Way.
        /// </summary>
        internal static string SpShipmentOnWay {
            get {
                return ResourceManager.GetString("SpShipmentOnWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting Shipment.
        /// </summary>
        internal static string SpWaitingShipment {
            get {
                return ResourceManager.GetString("SpWaitingShipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StockMount on GitHub.
        /// </summary>
        internal static string StockMountGitHub {
            get {
                return ResourceManager.GetString("StockMountGitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StockMount Website.
        /// </summary>
        internal static string StockMountSite {
            get {
                return ResourceManager.GetString("StockMountSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StopProduct.
        /// </summary>
        internal static string StopProductService {
            get {
                return ResourceManager.GetString("StopProductService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This function stops selling for a product with a given id.
        /// </summary>
        internal static string StopProductServiceDescription {
            get {
                return ResourceManager.GetString("StopProductServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Id.
        /// </summary>
        internal static string StoreId {
            get {
                return ResourceManager.GetString("StoreId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitle.
        /// </summary>
        internal static string Subtitle {
            get {
                return ResourceManager.GetString("Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Rate.
        /// </summary>
        internal static string TaxRate {
            get {
                return ResourceManager.GetString("TaxRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try out.
        /// </summary>
        internal static string TestService {
            get {
                return ResourceManager.GetString("TestService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateProduct.
        /// </summary>
        internal static string UpdateProductService {
            get {
                return ResourceManager.GetString("UpdateProductService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This function updates the product with the given id and parameters.
        /// </summary>
        internal static string UpdateProductServiceDescription {
            get {
                return ResourceManager.GetString("UpdateProductServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        internal static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User message.
        /// </summary>
        internal static string UserMessage {
            get {
                return ResourceManager.GetString("UserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration User Message Code.
        /// </summary>
        internal static string UserMessageCode {
            get {
                return ResourceManager.GetString("UserMessageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Message Id.
        /// </summary>
        internal static string UserMessageId {
            get {
                return ResourceManager.GetString("UserMessageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variant Name.
        /// </summary>
        internal static string VariantName {
            get {
                return ResourceManager.GetString("VariantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variants.
        /// </summary>
        internal static string Variants {
            get {
                return ResourceManager.GetString("Variants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variant value.
        /// </summary>
        internal static string VariantValue {
            get {
                return ResourceManager.GetString("VariantValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        internal static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
    }
}
